In [54]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/fredericobreno/play-tennis/play_tennis.csv
/kaggle/input/datasets/organizations/uciml/iris/Iris.csv
/kaggle/input/datasets/organizations/uciml/iris/database.sqlite

**Naive Bayes classification (internal workthrough)**

In [21]:
df_tennis = pd.read_csv('/kaggle/input/datasets/fredericobreno/play-tennis/play_tennis.csv')

In [22]:
df_tennis

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [23]:
df_tennis = df_tennis.drop(columns=['day'])

In [24]:
# problem 1
# outlook = sunny, temp = hot, humidity = high, wind = weak play or no play?
# outlook = overcast, temp = cold, humidity = low, wind = weak play or no play?

In [25]:
# P(yes | sunny, hot, high, weak) = P(sunny | yes) * P(hot | yes) * P(high | yes) * P(weak | yes) * P(yes)
# P(no | sunny, hot, high, weak) = P(sunny | no) * P(hot | no) * P(high | no) * P(weak | no) * P(no)

In [26]:
df_tennis['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [27]:
py = 9/14
pn = 5/14

In [28]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [29]:
# outlook
pd.crosstab(df_tennis['outlook'], df_tennis['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [40]:
pOvercastN = 0
pRainN = 2/5
pSunnyN = 3/5

pOvercastY = 4/9
pRainY = 3/9
pSunnyY = 2/9

In [31]:
pd.crosstab(df_tennis['temp'], df_tennis['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [37]:
pCoolN = 1/5
pHotN = 2/5
pMildN = 2/5

pCoolY = 3/9
pHotY = 2/9
pMildY = 4/9

In [33]:
pd.crosstab(df_tennis['humidity'], df_tennis['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [42]:
pHighN = 4/5
pNormalN = 1/5

pHighY = 3/9
pNormalY = 6/9

In [35]:
pd.crosstab(df_tennis['wind'], df_tennis['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [38]:
pStrongN = 3/5
pWeakN = 2/5

pStrongY = 3/9
pWeakY = 6/9

In [44]:
# P(yes | sunny, hot, high, weak) = P(sunny | yes) * P(hot | yes) * P(high | yes) * P(weak | yes) * P(yes)

pYes = pSunnyY * pHotY * pHighY * pWeakY * py
print(pYes)

0.007054673721340387

In [46]:
pNo = pSunnyN * pHotN * pHighN * pWeakN * pn
print(pNo)

0.02742857142857143

In [47]:
df_iris = pd.read_csv('/kaggle/input/datasets/organizations/uciml/iris/Iris.csv')

In [48]:
df_iris

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [52]:
df_iris = df_iris.drop(columns = ['Id'])

In [53]:
df_iris

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [65]:
x = df_iris.drop(columns = ['Species'])
y = df_iris['Species']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [66]:
# model creation
model = GaussianNB()

In [67]:
# Tran model
model.fit(x_train, y_train)

GaussianNB()

In [68]:
#prediction
y_pred = model.predict(x_test)

In [69]:
# accuracy check
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

1.0

In [70]:
# predict item
flower_1 = [[5.1, 3.5, 1.4, 0.2]]
pred_1 = model.predict(flower_1)
print("The flower is: ", pred_1[0])

The flower is:  Iris-setosa

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(